--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/BedrockQuest
build-by-default: true
branches:
  - main
projects:
  BedrockQuest:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        branch: master
        version: ^4.0.1
...
