---
name: BedrockQuest
author: alvin0319
main: alvin0319\BedrockQuest\BedrockQuest
version: 1.0.0
api: 3.0.0
permissions:
  smeltquest.command.use:
    default: true
  smeltquest.command.manage:
    default: op
...
